version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: "/next-app"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      radix:
        patterns:
          - "@radix-ui/*"
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
