version: '3.8'

# Enable BuildKit by default
x-build-args: &build-args
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

services:
  # Development service
  frontend-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        <<: *build-args
        NODE_ENV: development
    volumes:
      - /app/node_modules
      - ${HOME}/.npm:/root/.npm:cached
    ports:
      - "${PORT:-5173}:5173"
      - "24678:24678"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-https://radius.xnetcloud.tech/api}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontend-network

  # Production service
  frontend-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *build-args
        NODE_ENV: production
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
      cache_from:
        - type=registry,ref=node:20-alpine
        - type=registry,ref=nginx:alpine-slim
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontend-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M

networks:
  frontend-network:
    driver: bridge 