FROM node:20-slim

ENV NODE_ENV=development
WORKDIR /app

COPY . .

WORKDIR /app/next-app
RUN npm ci --legacy-peer-deps

ENV PATH=/app/next-app/node_modules/.bin:$PATH
EXPOSE 5173

CMD ["npx", "next", "dev", "--hostname", "0.0.0.0", "--port", "5173"]
