export const CABLE_VISION_TEXT = {
  pageTitle: "Cable Vision",
  pageSubtitle: "Track accounts, 5 profile/device slots, and monthly payments",
  monthLabel: "Month",
  totalLabel: "Total",
  refresh: "Refresh",
  refreshToastTitle: "Refreshed",
  refreshToastDescription: "Cable Vision accounts updated.",
  generateInvoices: "Generate invoices",
  generateInvoicesNoPerm: "You don't have permission to generate invoices.",
  generateInvoicesHint: "Generate invoices for active profiles",
  newAccount: "New account",
  newAccountNoPerm: "You don't have permission to manage Cable Vision accounts.",
  searchPlaceholder: "Search by account number, name, or phone…",
  pageSizeLabel: "Page size",

  emptyTitle: "No Cable Vision accounts",
  emptyDescriptionManage: "Create your first account to start tracking profiles and payments.",
  emptyDescriptionNoManage: "You don't have permission to create accounts. Ask an admin to grant cablevision.accounts.manage.",

  table: {
    account: "Account",
    customer: "Customer",
    profiles: "Profiles",
    thisMonth: "This month",
    actions: "Actions",
    details: "Details",
    hide: "Hide",
    addProfile: "Add profile",
    addProfileNoPerm: "You don't have permission to manage accounts.",
    profilesSection: "Profiles",
    slot: "Slot",
    profile: "Profile",
    user: "User",
    fee: "Fee",
    invoice: "Invoice",
    noProfiles: "No profiles yet. Add up to 5 profiles/devices for this account.",
    devicePrefix: "Device:",
    noInvoice: "No invoice",
    generateInvoice: "Generate invoice",
    generateInvoiceHint: "No invoice for this month. Generate invoices first.",
    markPaid: "Mark paid",
    markPaidNoPerm: "You don't have permission to pay invoices.",
    markUnpaid: "Mark unpaid",
    markUnpaidNoPerm: "You don't have permission to unpay invoices.",
    edit: "Edit",
  },

  dialogs: {
    createAccountTitle: "New Cable Vision account",
    accountNumberLabel: "Account number",
    accountNumberPlaceholder: "e.g. CV-000123",
    customerNameLabel: "Customer name",
    customerNamePlaceholder: "Full name",
    phoneLabel: "Phone",
    phonePlaceholder: "Phone",
    emailLabel: "Email",
    emailPlaceholder: "Email",
    cancel: "Cancel",
    create: "Create",

    addProfileTitle: "Add profile/device",
    profileNameLabel: "Profile name",
    profileNamePlaceholder: "e.g. Device 1 / Profile A",
    assignedToLabel: "Assigned to",
    assignedToPlaceholder: "Optional user name",
    deviceIdLabel: "Device ID",
    deviceIdPlaceholder: "Optional device id / MAC / STB id",
    monthlyFeeLabel: "Monthly fee",
    monthlyFeePlaceholder: "e.g. 10",
    add: "Add",

    editProfileTitle: "Edit profile/device",
    save: "Save",
  },
} as const;

