#!/bin/sh
set -eu

API_URL="${API_URL:-${VITE_API_URL:-https://api.xnetcloud.tech/api}}"
export API_URL

DEFAULT_NAS_IP="${DEFAULT_NAS_IP:-${VITE_DEFAULT_NAS_IP:-}}"
DEFAULT_NAS_SECRET="${DEFAULT_NAS_SECRET:-${VITE_DEFAULT_NAS_SECRET:-}}"
DEFAULT_NAS_COA_PORT="${DEFAULT_NAS_COA_PORT:-${VITE_DEFAULT_NAS_COA_PORT:-1700}}"
export DEFAULT_NAS_IP DEFAULT_NAS_SECRET DEFAULT_NAS_COA_PORT

APP_VERSION="${APP_VERSION:-${VITE_APP_VERSION:-}}"
APP_BUILD_TIME="${APP_BUILD_TIME:-${VITE_APP_BUILD_TIME:-}}"
APP_GIT_SHA="${APP_GIT_SHA:-${VITE_APP_GIT_SHA:-}}"
export APP_VERSION APP_BUILD_TIME APP_GIT_SHA

SENTRY_DSN="${SENTRY_DSN:-${VITE_SENTRY_DSN:-}}"
SENTRY_ENVIRONMENT="${SENTRY_ENVIRONMENT:-${VITE_SENTRY_ENVIRONMENT:-}}"
export SENTRY_DSN SENTRY_ENVIRONMENT

FEATURE_FLAGS="${FEATURE_FLAGS:-${VITE_FEATURE_FLAGS:-}}"
export FEATURE_FLAGS

TEMPLATE="${PWD}/public/env.template.js"
OUT="${PWD}/public/env.js"

if [ -f "$TEMPLATE" ]; then
  envsubst '${API_URL} ${FEATURE_FLAGS} ${DEFAULT_NAS_IP} ${DEFAULT_NAS_SECRET} ${DEFAULT_NAS_COA_PORT} ${SENTRY_DSN} ${SENTRY_ENVIRONMENT} ${APP_VERSION} ${APP_BUILD_TIME} ${APP_GIT_SHA}' < "$TEMPLATE" > "$OUT"
else
  echo "window.__ENV__ = window.__ENV__ || {};" > "$OUT"
fi

exec node server.js
